name: Build and Deploy to staging

on:
  pull_request:
    branches: [main]

env:
  AZURE_WEBAPP_NAME: httpstatus-preview
  IMAGE_NAME: ${{ github.repository }}-staging

permissions:
  id-token: write
  contents: read

jobs:
  build-images:
    runs-on: ubuntu-latest
    name: Build Docker images for Azure Container Registry and GitHub Container Registry
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io/sarathkrishnamurthy/httpstatus
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: docker buildx build
        run: |
          docker buildx build --push --platform linux/arm64 -t ghcr.io/sarathkrishnamurthy/httpstatus:test -f src/Teapot.Web/Dockerfile . 
